deploy.yaml
docs/vars.md
inventories/example_local/group_vars/dojot-k8s/dojot.yaml
roles/apigw/tasks/main.yaml
roles/auth/defaults/main.yaml
roles/auth/tasks/main.yaml
roles/auth/templates/auth_deployment.yaml.j2
roles/auth/templates/auth_secrets.yaml.j2
roles/data-broker/tasks/main.yaml
roles/data-manager/tasks/main.yaml
roles/databases/mongodb/tasks/main.yaml
roles/databases/postgresql/tasks/main.yaml
roles/device-manager/tasks/main.yaml
roles/dojot-basic/defaults/main.yaml
roles/dojot-basic/tasks/main.yaml
roles/dojot-basic/templates/namespace.yaml.j2
roles/flowbroker/tasks/main.yaml
roles/gui/tasks/main.yaml
roles/history/tasks/main.yaml
roles/iotagent-mosca/tasks/main.yaml
roles/k8s-api-bootstrap/tasks/main.yaml
roles/kafka/tasks/main.yaml
roles/persister/tasks/main.yaml
roles/rabbitmq/tasks/main.yaml
roles/zookeeper/defaults/main.yaml
roles/zookeeper/tasks/main.yaml

* [ X ] Docs have been added / updated (for bug fixes / features)
Improvements
No
No
- Add default empty value for kubeconfig file
- Aggregate kubernetes object with same deployment method
- Adds retries for objects deployment to K8s
- Treat no email configuration for the auth service

Improvements to file organization

---

docs/vars.md
requirements.txt
roles/apigw/defaults/main.yaml
roles/apigw/vars/main.yaml
roles/auth/defaults/main.yaml
roles/auth/templates/auth_deployment.yaml.j2
roles/data-broker/defaults/main.yaml
roles/data-broker/templates/data_broker_deployment.yaml.j2
roles/data-manager/defaults/main.yaml
roles/data-manager/templates/data_manager_deployment.yaml.j2
roles/device-manager/defaults/main.yaml
roles/device-manager/templates/device_manager_deployment.yaml.j2
roles/flowbroker/defaults/main.yaml
roles/flowbroker/templates/flowbroker_deployment.yaml.j2
roles/gui/defaults/main.yaml
roles/gui/templates/gui_deployment.yaml.j2
roles/history/defaults/main.yaml
roles/history/templates/history_deployment.yaml.j2
roles/iotagent-mosca/defaults/main.yaml
roles/iotagent-mosca/templates/iotagent_mosca_deployment.yaml.j2
roles/persister/defaults/main.yaml
roles/persister/templates/persister_deployment.yaml.j2

* [ X ] Docs have been added / updated (for bug fixes / features)
Feature
All containers are started using the content of the dojot_version varaible
All containers might have their version individually selected rather than just using the dojot_version value.
no
no

Adds configuration to specialize container version as necessary

---

deploy.yaml
docs/vars.md
inventories/example_local/group_vars/dojot-k8s/dojot.yaml
requirements.txt
roles/auth/templates/auth_deployment.yaml.j2
roles/data-broker/templates/data_broker_deployment.yaml.j2
roles/ejbca-rest/defaults/main.yaml
roles/ejbca-rest/tasks/main.yaml
roles/ejbca-rest/templates/ejbca_deployment.yaml.j2
roles/ejbca-rest/templates/ejbca_pvc.yaml.j2
roles/ejbca-rest/templates/ejbca_service.yaml.j2
roles/flowbroker/templates/flowbroker_deployment.yaml.j2
roles/history/templates/history_deployment.yaml.j2
roles/iotagent-mosca/defaults/main.yaml
roles/iotagent-mosca/templates/iotagent_mosca_deployment.yaml.j2
roles/persister/templates/persister_deployment.yaml.j2

* [NA] Tests for the changes have been added (for bug fixes / features)
* [NA] Docs have been added / updated (for bug fixes / features)
Small change to the examples and requirements

Requirement and example fixes

---

roles/ejbca-rest/tasks/main.yaml

Bug Fix
The current behavior doesnt verify if persistent volumes are enabled before creating a PVC foe ejbca
Now persitent volumes are checked before creating a PVC for ejbca
no
no

Fix ejbca deployment without persistent volumes

---

roles/flowbroker/templates/flowbroker_deployment.yaml.j2

Bug fix
Context manager can't access zookeeper on k8s
Context manager can access zookeeper on k8s
No
Yes, this issue is connected to dojot/dojot#1318

bugfix zookeeper host variable on k8s

---

inventories/example_local/group_vars/dojot-k8s/dojot.yaml
roles/flowbroker/templates/flowbroker_deployment.yaml.j2

Are these corrections necessary in dev?

Release/v0.4.1 to Dev

---

roles/apigw/templates/apigw_routes_config_map.yaml.j2

dojot/dojot#1354
dojot/dojot#1337

fix: add auth/pap, ejbca /user and mqtt metrics

---

roles/apigw/templates/apigw_routes_config_map.yaml.j2

fix invisibles spaces and tabs

---

roles/flowbroker/templates/flowbroker_role.yaml.j2

Bugfix flowbroker permissions to call patch and delete on Kubernetes API
Flowbroker has not permissions to call patch and delete on Kubernetes API
Flowbroker has permissions to call patch and delete on Kubernetes API
No
Yes, this PR is connected to dojot/dojot#1348

add flowbroker permissions for delete and patch

---

inventories/example_local/group_vars/dojot-k8s/dojot.yaml
roles/apigw/templates/apigw_routes_config_map.yaml.j2
roles/flowbroker/templates/flowbroker_role.yaml.j2

Release/v0.4.2 to Master

---

docs/vars.md
inventories/example_local/group_vars/dojot-k8s/dojot.yaml

Bug fix
dojot/dojot#1410
Set MQTT variable to allow unsecured mode.

[fix] set dojot mqtt unsecured mode

---

roles/apigw/tasks/main.yaml
roles/apigw/templates/apigw_external_service.yaml.j2
roles/apigw/vars/main.yaml
roles/iotagent-mosca/templates/iotagent_mosca_service.yaml.j2

fix:  not expose kong admin port

---

roles/apigw/templates/apigw_deployment.yaml.j2
roles/auth/templates/auth_deployment.yaml.j2
roles/backstage/templates/backstage_deployment.yaml.j2
roles/cron/templates/cron_deployment.yaml.j2
roles/data-broker/templates/data_broker_deployment.yaml.j2
roles/data-broker/templates/data_broker_redis_deployment.yaml.j2
roles/data-manager/templates/data_manager_deployment.yaml.j2
roles/databases/mongodb/templates/mongodb_deployment.yaml.j2
roles/databases/postgresql/templates/postgres_deployment.yaml.j2
roles/device-manager/templates/device_manager_deployment.yaml.j2
roles/device-manager/templates/device_manager_redis_deployment.yaml.j2
roles/flowbroker/templates/flowbroker_deployment.yaml.j2
roles/gui/templates/gui_deployment.yaml.j2
roles/history/templates/history_deployment.yaml.j2
roles/image-manager/templates/image_manager_deployment.yaml.j2
roles/iotagent-lwm2m/templates/iotagent_lwm2m_deployment.yaml.j2
roles/iotagent-mosca/templates/iotagent_mosca_deployment.yaml.j2
roles/kafka/templates/kafka_statefulset.yaml.j2
roles/kafka2ftp/templates/kafk2ftp_deployment.yaml.j2
roles/metrics/templates/0prometheus-operator-deployment.yaml
roles/metrics/templates/grafana-deployment.yaml
roles/metrics/templates/kube-state-metrics-deployment.yaml
roles/metrics/templates/node-exporter-daemonset.yaml
roles/minio/templates/minio_statefulset.yaml.j2
roles/persister/templates/persister_deployment.yaml.j2
roles/rabbitmq/templates/rabbitmq_deployment.yaml.j2
roles/vernemq/templates/vernemq_operator_deployment.yaml.j2
roles/zookeeper/templates/zk_statefulset.yaml.j2

dojot update to works on k8s 1.17
dojot only works on k8s 1.15
dojot works on k8s 1.17
No
Yes, this PR is related to dojot/dojot#1495

upgrade k8s 1.17

---

roles/vernemq/templates/vernemq_external_service.yaml.j2

Verne's external clients connect to local pods
Verne's external clients connect to random pods
Verne's external clients connect to local pods
No
Yes, this PR is related to dojot/dojot#1495

change of the verne external traffic policy

---

roles/databases/postgres-ejbca/templates/postgres_statefulset.yaml.j2

Bug fix.
The variable `dojot_ejbca_psql_persistent_volumes` is declared, but `dojot_psql_ejbca_persistent_volumes` is used instead.
Correct the variable name.
No.

Fix variable name

---

deploy.yaml
roles/apigw/tasks/main.yaml
roles/apigw/templates/apigw_migration_up_job.yaml.j2
roles/apigw/templates/apigw_routes_config_map.yaml.j2
roles/databases/postgresql/defaults/main.yaml

Is there any issue related to this PR in other repository? (such as dojot/dojot)
dojot/dojot#1467 - upgrade kong to 2.x
dojot/dojot#1388 - Backstage route 
dojot/dojot#1422 - kafka-ws route
dojot/dojot#1469 - x509-identity-mgmt route
Depends 
https://github.com/dojot/kong/pull/18

chore: upgrade kong to 2.x and add some new routes

---

docs/vars.md
inventories/example_local/group_vars/dojot-k8s/dojot.yaml
roles/apigw/templates/apigw_external_service.yaml.j2
roles/metrics/tasks/main.yaml
roles/metrics/templates/grafana-external-service.yaml.j2
roles/metrics/templates/grafana-internal-service.yaml
roles/vernemq/templates/vernemq_external_service.yaml.j2

Se fixed NodePorts in variables file
You need to set fixed NodePorts in service role
Fixes NodePorts in variables file
No
No

fixed node ports in the variables file

---

roles/x509-identity-mgmt/templates/x509_identity_mgmt_deployment.yaml.j2

Change x509 default number of replicas to 1

---

roles/apigw/tasks/main.yaml
roles/apigw/templates/apigw_external_service.yaml.j2
roles/apigw/vars/main.yaml
roles/iotagent-mosca/templates/iotagent_mosca_service.yaml.j2

fix: not expose kong admin port [release v0.4.3]

---

inventories/example_local/group_vars/dojot-k8s/dojot.yaml
roles/iotagent-lwm2m/defaults/main.yaml
roles/iotagent-lwm2m/templates/iotagent_lwm2m_deployment.yaml.j2
roles/iotagent-mosca/templates/iotagent_mosca_deployment.yaml.j2

chore: create version v0.4.3-rc.1

---

deploy.yaml
docs/vars.md
inventories/example_local/group_vars/dojot-k8s/dojot.yaml
roles/apigw/templates/apigw_routes_config_map.yaml.j2
roles/gui-v2/defaults/main.yaml
roles/gui-v2/tasks/main.yaml
roles/gui-v2/templates/gui_deployment.yaml.j2
roles/gui-v2/templates/gui_service.yaml.j2

feature
We don't have GUI V2 deployment
GUI V2 deployment
No
Yes, this PR is connected to dojot/dojot#1615 and dojot/dojot#1603

GUI V2 deployment

---

roles/nginx/defaults/main.yaml
roles/nginx/tasks/main.yaml

Bug fix
Version 1.19 is not available on Ubuntu 18.04 and it's not stable.
Changed to stable version 1.18
No
Yes, this PR is connected to dojot/dojot#1600

nginx version and update cache

---

roles/databases/mongodb/templates/mongodb_statefulset.yaml.j2
roles/x509-identity-mgmt/templates/x509_identity_mgmt_deployment.yaml.j2

Correct identation

---

roles/zookeeper/templates/zk_statefulset.yaml.j2

Bug fix
Node affinity label is wrong
Set "kafka" as node affinity label
No
No

zookeeper node affinity label

---

docs/vars.md
inventories/example_local/group_vars/dojot-k8s/dojot.yaml
roles/apigw/tasks/main.yaml
roles/apigw/templates/apigw_external_service.yaml.j2
roles/apigw/vars/main.yaml
roles/iotagent-lwm2m/defaults/main.yaml
roles/iotagent-lwm2m/templates/iotagent_lwm2m_deployment.yaml.j2
roles/iotagent-mosca/templates/iotagent_mosca_deployment.yaml.j2
roles/iotagent-mosca/templates/iotagent_mosca_service.yaml.j2

merge v0.4.3 to master

---

README.md
scripts/down
scripts/up

Feature
Add the up and down scripts.
No.

[dev] Add utility scripts

---

README.md
scripts/down
scripts/up

Feature
Add the up and down scripts.
No.

[v0.5.0] Add utility scripts

---

roles/apigw/templates/apigw_deployment.yaml.j2
roles/auth/templates/auth_deployment.yaml.j2
roles/backstage/templates/backstage_deployment.yaml.j2
roles/cron/templates/cron_deployment.yaml.j2
roles/data-broker/templates/data_broker_deployment.yaml.j2
roles/data-broker/templates/data_broker_redis_deployment.yaml.j2
roles/data-manager/templates/data_manager_deployment.yaml.j2
roles/databases/mongodb/templates/mongodb_deployment.yaml.j2
roles/databases/postgresql/templates/postgres_deployment.yaml.j2
roles/device-manager/templates/device_manager_deployment.yaml.j2
roles/device-manager/templates/device_manager_redis_deployment.yaml.j2
roles/ejbca-rest/templates/ejbca_deployment.yaml.j2
roles/flowbroker/templates/flowbroker_deployment.yaml.j2
roles/gui/templates/gui_deployment.yaml.j2
roles/history/templates/history_deployment.yaml.j2
roles/image-manager/templates/image_manager_deployment.yaml.j2
roles/iotagent-lwm2m/templates/iotagent_lwm2m_deployment.yaml.j2
roles/iotagent-mosca/templates/iotagent_mosca_deployment.yaml.j2
roles/kafka/templates/kafka_statefulset.yaml.j2
roles/minio/templates/minio_statefulset.yaml.j2
roles/persister/templates/persister_deployment.yaml.j2
roles/rabbitmq/templates/rabbitmq_deployment.yaml.j2
roles/zookeeper/templates/zk_statefulset.yaml.j2

dojot v0.4.4 now works on k8s 1.17
previous dojot versions only work on k8s 1.15
dojot v0.4.4 works on k8s 1.17
No
Yes, this PR is related to dojot/dojot#1705

v0.4.4 upgrade k8s 1.17

---

roles/flowbroker/templates/flowbroker_role.yaml.j2

Changing rule for flowbroker

---

roles/flowbroker/templates/flowbroker_role.yaml.j2

Change rule for flowbroker

---

roles/gui-v2/defaults/main.yaml

chore: change to public img for gui-v2

---

roles/flowbroker/templates/flowbroker_role.yaml.j2

Change name of apiGroups

---

roles/flowbroker/templates/flowbroker_role.yaml.j2

Changing apiGroups

---

roles/v2k-bridge/templates/v2k_bridge_cluster.yaml.j2

Update in component
Since V2K is now using the SDK ConfigManager, this PR adequates its parameters for the new patterns.
Yes, some environment variables names are different.
Related to this PR: https://github.com/dojot/dojot/pull/1781

Modify V2K environment variables

---

roles/apigw/vars/main.yaml
roles/auth/defaults/main.yaml
roles/auth/templates/auth_deployment.yaml.j2
roles/auth/vars/main.yaml
roles/metrics/defaults/main.yaml

Yes, this PR is connected to dojot/dojot#1735

Standardize ansible variables

---

inventories/example_local/group_vars/all/dojot.yaml
roles/kafka-ws/templates/kafka_ws_deployment.yaml.j2

fix env kafka-ws and bump to v0.5.0-rc.2

---

docs/vars.md
roles/k8s-cluster/all-nodes/defaults/main.yaml
roles/k8s-cluster/all-nodes/handlers/main.yaml
roles/k8s-cluster/all-nodes/tasks/main.yaml
roles/k8s-cluster/all-nodes/templates/docker-daemon.json.j2

Bug
The log file of the containers grow without limits
The log file has a maximum size of 100m, and can be customized.
No
Yes, this PR is connected to dojot/dojot#1854

docker log file size

---

roles/k2v-bridge/templates/k2v_bridge_cluster.yaml.j2

Feature
Verifies the health check that K2V provides.
No.
https://github.com/dojot/dojot/issues/1849

[k2v] Add probes

---

docs/vars.md
inventories/example_local/group_vars/all/dojot.yaml
inventories/example_local/hosts.yaml
nginx.yaml
roles/apigw/templates/apigw_external_service.yaml.j2
roles/iotagent-lwm2m/templates/iotagent_lwm2m_service.yaml.j2
roles/iotagent-mosca/templates/iotagent_mosca_service.yaml.j2
roles/nginx/defaults/main.yaml
roles/nginx/handlers/main.yml
roles/nginx/tasks/main.yaml
roles/nginx/templates/apigw.conf.j2
roles/nginx/templates/coap.conf.j2
roles/nginx/templates/coap_http.conf.j2
roles/nginx/templates/coaps.conf.j2
roles/nginx/templates/file_server.conf.j2
roles/nginx/templates/file_servers.conf.j2
roles/nginx/templates/mqtt.conf.j2
roles/nginx/templates/mqtts.conf.j2
roles/nginx/templates/nginx.conf.j2

Feature
We don't have a load balancer for dojot v0.4.4
Nginx will be used as a load balancer
No
Yes, this PR is connected to dojot/dojot#1863 and dojot/dojot#1837

[v0.4.4] Nginx deployment

---

deploy.yaml
docs/vars.md
inventories/example_local/group_vars/all/dojot.yaml
inventories/example_local/group_vars/all/services.yaml
local_storage_example/volumes/influxdb.yaml
roles/apigw/templates/apigw_routes_config_map.yaml.j2
roles/databases/influxdb/defaults/main.yaml
roles/databases/influxdb/tasks/main.yaml
roles/databases/influxdb/templates/influxdb_job_setup.yaml.j2
roles/databases/influxdb/templates/influxdb_secret.yaml.j2
roles/databases/influxdb/templates/influxdb_service.yaml.j2
roles/databases/influxdb/templates/influxdb_statefulset.yaml.j2
roles/history/tasks/main.yaml
roles/influxdb-retriever/defaults/main.yaml
roles/influxdb-retriever/tasks/main.yaml
roles/influxdb-retriever/templates/influxdb_retriever_deployment.yaml.j2
roles/influxdb-retriever/templates/influxdb_retriever_service.yaml.j2
roles/influxdb-storer/defaults/main.yaml
roles/influxdb-storer/tasks/main.yaml
roles/influxdb-storer/templates/influxdb_storer_deployment.yaml.j2
roles/persister/tasks/main.yaml

Feature
There is no deployment of InfluxDB services
Deployment of InfluxDB services
No
Yes, this PR is connected to dojot/dojot#1883

[v0.5.1] add influxdb, storer and retriever

---

deploy.yaml

* Bug fix
* The order of the deploy is wrong, as vernemq needs objects from the metrics service
* The metrics service must be deployed first
No
* No

[v0.5.1] metrics deploy order

---

roles/nginx/tasks/main.yaml

Fixing nginx syntax error

---

roles/kafka2ftp/templates/kafk2ftp_deployment.yaml.j2

dojot/dojot#1900
dojot/dojot#1879

[dev] change env name to kafka2ftp 

---

roles/apigw/templates/apigw_migration_job.yaml.j2

fix: Kong image tag

---

deploy.yaml

* Bug fix
* The order of the deploy is wrong, as vernemq needs objects from the metrics service
* The metrics service must be deployed first
No
* No

[dev] metrics deploy order

---

LICENSE
README.md

It changes the license to Apache-2.0
NA
NA
No
dojot/dojot#1879

Changed license from GPL-v3 to Apache

---

docs/vars.md
roles/databases/influxdb/defaults/main.yaml

Improve comments for influxdb retention

---

LICENSE
README.md
docs/vars.md
inventories/example_local/group_vars/all/dojot.yaml
roles/databases/influxdb/defaults/main.yaml

[v0.5.2] Cherry-picking licenses from development

---

roles/kafka-ws/templates/kafka_ws_deployment.yaml.j2

fixed readiness and liveness prob for kafka-ws
updated redis host default env variable for kafka-ws
bug fix
* #dojot/dojot/1973

[dev] kafka-ws fix readiness and liveness prove

---

roles/kafka-ws/templates/kafka_ws_deployment.yaml.j2

fixed readiness and liveness prob for kafka-ws
updated redis host default env variable for kafka-ws
bug fix
* #dojot/dojot/1973

Kafka-ws fix readness and liveness prove

---

inventories/example_local/group_vars/all/dojot.yaml

bump to v0.6.0-rc.1

---

deploy.yaml
docs/vars.md
inventories/example_local/group_vars/all/services.yaml
roles/iotagent-lwm2m/tasks/main.yaml
roles/iotagent-mosca/tasks/main.yaml
roles/vernemq/tasks/main.yaml

Enhancement
You can chose the IotAgent to be deployed using ansible tags
You can chose the IotAgent to be deployed using services.yaml file
No
Yes, this PR is connected to dojot/dojot#1991

[Ansible] Chose the IotAgent to be deployed in services.yaml file

---

roles/k8s-cluster/all-nodes/defaults/main.yaml
roles/k8s-cluster/all-nodes/tasks/main.yaml
roles/k8s-cluster/master-node/defaults/main.yaml
roles/k8s-cluster/master-node/templates/config.yaml.j2

Feature
The supported version of kubernetes is 1.17
Support for kubernetes version 1.19
No
Yes, this PR is connected to dojot/dojot#1908

Upgrade k8s version to 1.19.8

---

inventories/example_local/group_vars/all/dojot.yaml

Update dojot version to v0.6.0-rc.3

---

inventories/example_local/group_vars/all/dojot.yaml
local_storage_example/volumes/kafka.yaml
local_storage_example/volumes/x509_identity_mgmt.yaml
local_storage_example/volumes/zookeeper_data.yaml
local_storage_example/volumes/zookeeper_log.yaml
roles/x509-identity-mgmt/templates/x509_identity_mgmt_deployment.yaml.j2
scripts/down
scripts/up

Bug fix
The volumes are not configured to be created
As the EJBCA always needs a volume, then volume creation has been enabled for all Pods that need them.
dojot/dojot#2083
- Example volume labels in `./local_storage_example/volumes/*` have been changed to the same value: …

Release/v0.6.0 - use of volumes enabled by default

---

docs/vars.md
roles/kafka-ws/defaults/main.yaml
roles/kafka-ws/templates/kafka_ws_deployment.yaml.j2

note: secret kafka-ws

---

roles/volumes/certificate-acl/tasks/main.yaml
roles/volumes/influxdb/tasks/main.yaml
roles/volumes/kafka-ws/tasks/main.yaml
roles/volumes/kafka/tasks/main.yaml
roles/volumes/kong/tasks/main.yaml
roles/volumes/minio/tasks/main.yaml
roles/volumes/mongodb/tasks/main.yaml
roles/volumes/postgres/tasks/main.yaml
roles/volumes/prometheus/tasks/main.yaml
roles/volumes/x509-ejbca/tasks/main.yaml
roles/volumes/x509-identity-mgmt/tasks/main.yaml
roles/volumes/zookeeper/tasks/main.yaml

Bug fix
The volume playbook is not working with old versions of ansible, python and pip3
The syntax of the volumes tasks was changed in order to work with a wide range of versions
No
dojot/dojot#2172

[Dev] Fix dojot volumes syntax

---

roles/volumes/certificate-acl/tasks/main.yaml
roles/volumes/influxdb/tasks/main.yaml
roles/volumes/kafka-ws/tasks/main.yaml
roles/volumes/kafka/tasks/main.yaml
roles/volumes/kong/tasks/main.yaml
roles/volumes/minio/tasks/main.yaml
roles/volumes/mongodb/tasks/main.yaml
roles/volumes/postgres/tasks/main.yaml
roles/volumes/prometheus/tasks/main.yaml
roles/volumes/x509-ejbca/tasks/main.yaml
roles/volumes/x509-identity-mgmt/tasks/main.yaml
roles/volumes/zookeeper/tasks/main.yaml

Bug fix
The volume playbook is not working with old versions of ansible, python and pip3
The syntax of the volumes tasks was changed in order to work with a wide range of versions
No
dojot/dojot#2172

[v0.7.0] Fix dojot volumes syntax

---

deploy.yaml

[Dev] Add 100k tag to InfluxDB and Certificate ACL

---

deploy.yaml

Add 100k tag to InfluxDB and Certificate ACL

---

inventories/example_local/group_vars/all/dojot.yaml

bump to v0.7.0-rc.3

---

roles/v2k-bridge/defaults/main.yaml

bump to v0.6.1-rc.1

---

inventories/example_local/hosts.yaml
label.yaml
roles/k8s-cluster/all-nodes/defaults/main.yaml
roles/k8s-cluster/all-nodes/handlers/main.yaml
roles/k8s-cluster/all-nodes/tasks/main.yaml
roles/k8s-cluster/all-nodes/templates/99-kubernetes-cri.conf.j2
roles/k8s-cluster/all-nodes/templates/containerd.conf.j2
roles/k8s-cluster/all-nodes/templates/docker-daemon.json.j2
roles/k8s-cluster/master-node/templates/config.yaml.j2

Change the Kubernetes Container Runtime to containerd
dojot/dojot#1918

Changed the Kubernetes Container Runtime to containerd

---

inventories/example_local/group_vars/all/dojot.yaml
roles/v2k-bridge/defaults/main.yaml

Bump to v0.6.1

---

inventories/example_local/group_vars/all/dojot.yaml

Bump to v0.7.0-rc.4

---

inventories/example_local/group_vars/all/dojot.yaml

Bump to v0.7.0

---

inventories/example_local/group_vars/all/dojot.yaml

Bump to v0.7.1-rc.1

---

roles/apigw/templates/apigw_routes_config_map.yaml.j2

Feature: add global correlation-id plugin

---

inventories/example_local/group_vars/all/dojot.yaml

bump to v0.7.1-rc.2

---

deploy.yaml
inventories/example_local/group_vars/all/dojot.yaml
inventories/example_local/group_vars/all/services.yaml
roles/databases/influxdb/defaults/main.yaml
roles/databases/influxdb/tasks/main.yaml
roles/databases/influxdb/templates/influxdb_external_service.yaml.j2
roles/databases/influxdb/templates/influxdb_job_created_user.yaml.j2
roles/http-agent/defaults/main.yaml
roles/http-agent/tasks/main.yaml
roles/http-agent/templates/http_agent_redis_service.yaml.j2
roles/http-agent/templates/http_agent_redis_statefulset.yaml.j2
roles/influxdb-chronograf/defaults/main.yaml
roles/influxdb-chronograf/tasks/main.yaml
roles/influxdb-chronograf/templates/influxdb_chronograf_statefulset.yaml.j2
roles/nginx/tasks/main.yaml
roles/nginx/templates/influxdb_web.conf.j2
roles/volumes/influxdb-chronograf/tasks/main.yaml
roles/volumes/influxdb-chronograf/templates/influxdb-chronograf.yaml.j2
volume.yaml

Interface WEB InfluxDB and HTTP-Agent Redis
dojot/dojot#2387

[ansible-dojot] Interface WEB InfluxDB and HTTP-Agent Redis

---

roles/http-agent/templates/http_agent_cluster.yaml.j2

[ansible] Deployment - Update HTTP Agent

[ansible] Deployment - Update HTTP Agent

---

inventories/example_local/group_vars/all/dojot.yaml

Bump to v0.7.1-rc.3

---

inventories/example_local/group_vars/all/dojot.yaml
roles/certificate-acl/templates/certificate_acl_redis_statefulset.yaml.j2

Bump to v0.7.1-rc.4

---

inventories/example_local/group_vars/all/dojot.yaml

Bump to v0.7.1

---

README.md
ansible.cfg
deploy.yaml
roles/metrics/tasks/helm.yml
roles/metrics/tasks/loki.yml
roles/metrics/tasks/main.yaml
roles/metrics/tasks/promtail.yml
roles/metrics/templates/loki/loki-values.yml.j2
roles/volumes/loki/tasks/main.yaml
roles/volumes/loki/templates/loki.yaml.j2
volume.yaml

docs update and improvements.
- The loki volume is designed to use the local-path-provisioner as a dynamic storageclass.
- It is not written in the documentation that the user needs to install an ansible collection to use the helm.
- Ansible-lint claimed several points of improvement in tasks and playbooks.
- Now we have an ansible role to create a local directory and a Persistent Volume for loki.
- I added the necessary step to install the ansible collection in the documentation.
- I made the necessary …

Loki volume adjustments and code quality improvements for tasks and playbooks

---

roles/metrics/README.md
roles/metrics/templates/grafana/grafana-values.yml.j2
roles/metrics/templates/prometheus/prometheus-values.yml.j2

Feature and Docs update
Currently monitoring solution does not have an exporter to get verne and kong metrics.
Now, using helm, we've added verne and kong jobs.
No

Vernemq and kong jobs

---

roles/metrics/README.md
roles/metrics/templates/grafana/grafana-values.yml.j2
roles/metrics/templates/prometheus/prometheus-values.yml.j2

Feature and Docs update
Currently, the monitoring solution has no jobs to get metrics from influxdb.
Now, using helm, we've added influxdb job.
No

Including Influxdb job

---

inventories/example_local/hosts.yaml
k3s.yaml
roles/k3s-cluster/defaults/main.yml
roles/k3s-cluster/files/k3s-killall.sh
roles/k3s-cluster/files/k3s-uninstall.sh
roles/k3s-cluster/handlers/main.yml
roles/k3s-cluster/meta/main.yml
roles/k3s-cluster/tasks/main.yml
roles/k3s-cluster/templates/k3s.service.j2
roles/k3s-cluster/tests/inventory
roles/k3s-cluster/tests/test.yml
roles/k3s-cluster/vars/main.yml

K3s para ambientes on-premises
https://jira.cpqd.com.br/browse/DEVOPS-9

 K3s para ambientes on-premises

---

roles/metrics/README.md
roles/metrics/tasks/main.yaml
roles/metrics/tasks/postgres.yml
roles/metrics/templates/grafana/grafana-values.yml.j2
roles/metrics/templates/postgres-exporter/postgres-exporter-values.yml.j2
roles/metrics/templates/prometheus/prometheus-values.yml.j2

Feature and Docs update
Currently, the monitoring solution has no jobs to get metrics from postgres.
Now, using helm, we've added postgres exporter and job.
No

Including postgres exporter

---

roles/influxdb-retriever/defaults/main.yaml
roles/influxdb-retriever/templates/influxdb_retriever_deployment.yaml.j2

Fix influxdb-retriever connection with kafka-server

---

inventories/example_local/group_vars/all/dojot.yaml
roles/influxdb-retriever/defaults/main.yaml
roles/influxdb-retriever/templates/influxdb_retriever_deployment.yaml.j2
roles/metrics/tasks/grafana.yml
roles/metrics/templates/grafana/grafana-values.yml.j2
roles/metrics/templates/grafana/secrets-grafana.yml.j2

Merge 'release/v0.8.0' into development 

---

deploy.yaml
roles/k2v-bridge/tasks/main.yaml
roles/k2v-bridge/templates/k2v_bridge_cluster.yaml.j2
roles/k2v-bridge/templates/k2v_bridge_keda.yaml.j2
roles/keda/tasks/main.yml
roles/v2k-bridge/tasks/main.yaml
roles/v2k-bridge/templates/v2k_bridge_cluster.yaml.j2
roles/v2k-bridge/templates/v2k_bridge_keda.yaml.j2
roles/vernemq/defaults/main.yaml
roles/vernemq/tasks/main.yaml
roles/vernemq/templates/vernemq_hpa_cluster_keda.yaml.j2
roles/vernemq/templates/vernemq_operator_deployment.yaml.j2
roles/vernemq/templates/z_vernemq_cluster.yaml.j2

Merge 0.8.0 to dev

---

deploy.yaml
roles/helm/defaults/main.yaml
roles/helm/tasks/main.yaml
roles/helm/vars/main.yaml

feature.
The current behavior not have helm install
The new behavior is than now have helm install
No.
No.

add helm install

---

deploy.yaml
roles/helm/defaults/main.yaml
roles/helm/tasks/main.yaml
roles/helm/vars/main.yaml

Merge 'release/v0.8.0' into development

Merge 'release/v0.8.0' into development

---

docs/vars.md
inventories/example_local/group_vars/all/dojot.yaml
roles/apigw/defaults/main.yaml
roles/auth/defaults/main.yaml
roles/backstage/templates/backstage_deployment.yaml.j2
roles/certificate-acl/defaults/main.yaml
roles/cron/templates/cron_deployment.yaml.j2
roles/data-broker/defaults/main.yaml
roles/data-manager/defaults/main.yaml
roles/device-manager/defaults/main.yaml
roles/file-mgmt/defaults/main.yaml
roles/flowbroker/defaults/main.yaml
roles/gui-v2/defaults/main.yaml
roles/gui/defaults/main.yaml
roles/history/defaults/main.yaml
roles/http-agent/defaults/main.yaml
roles/image-manager/defaults/main.yaml
roles/influxdb-retriever/defaults/main.yaml
roles/influxdb-storer/defaults/main.yaml
roles/iotagent-lwm2m/defaults/main.yaml
roles/iotagent-mosca/defaults/main.yaml
roles/k2v-bridge/defaults/main.yaml
roles/kafka-loopback/defaults/main.yaml
roles/kafka-ws/defaults/main.yaml
roles/kafka2ftp/defaults/main.yaml
roles/persister/defaults/main.yaml
roles/v2k-bridge/defaults/main.yaml
roles/vernemq/defaults/main.yaml
roles/x509-ejbca/defaults/main.yaml
roles/x509-identity-mgmt/defaults/main.yaml

We have only `dojot_version`
Now we have `dojot_backend_version` and `dojot_frontend_version` 
No
No

Separate dojot_version into dojot_backend_version and dojot_frontend_version 

---

inventories/example_local/group_vars/all/dojot.yaml
roles/http-agent/templates/http_agent_cluster.yaml.j2

Bump to v0.8.0-rc.3

---

docs/vars.md
inventories/example_local/group_vars/all/dojot.yaml
roles/metrics-server/tasks/main.yaml

feature
metrics server installation for all cluster types
metrics server installation only for those who want to use k8s cluster
No

metrics server for just k8s

---

inventories/example_local/group_vars/all/dojot.yaml

Bump to v0.8.0-rc.4

---

deploy.yaml
inventories/example_local/group_vars/all/dojot.yaml
roles/basic-auth/defaults/main.yaml
roles/basic-auth/tasks/main.yaml
roles/basic-auth/templates/basic_auth_deployment.yaml.j2
roles/basic-auth/templates/basic_auth_external_service.yaml.j2
roles/basic-auth/templates/basic_auth_service.yaml.j2
roles/nginx/tasks/main.yaml
roles/nginx/templates/basic_auth.conf.j2

Include basic auth deploy

---

inventories/example_local/group_vars/all/dojot.yaml

Bump to v0.8.0-rc.5

---

roles/metrics/tasks/main.yaml
roles/metrics/tasks/monitoring-stack.yml
roles/metrics/templates/loki/loki-values.yml.j2
roles/metrics/templates/monitoring-stack/stack-values.yml.j2
roles/volumes/loki/templates/loki.yaml.j2

Update
Previously there were errors in the panels and the nodeport for grafana was not defined. In addition to a very high limit for loki's volume.
Now the 100K dashboard is fixed, the loki volume is at a fair value and the grafana nodeport has been declared.

Fixing monitoring service

---

requirements.txt
roles/undeploy/dojot-volumes/directory/database/tasks/main.yaml
roles/undeploy/dojot-volumes/directory/dojot/tasks/main.yaml
roles/undeploy/dojot-volumes/directory/kafka/tasks/main.yaml
roles/undeploy/dojot-volumes/directory/x509/tasks/main.yaml
roles/undeploy/dojot-volumes/tasks/main.yaml
roles/undeploy/dojot/tasks/main.yaml
roles/undeploy/monitoring-volumes/directory/tasks/main.yaml
roles/undeploy/monitoring-volumes/tasks/main.yaml
roles/undeploy/monitoring/tasks/main.yaml
undeploy.yaml

Feature
Now it is possible to undeploy dojot using a playbook
No
[DEVOPS-362](https://jira.cpqd.com.br/browse/DEVOPS-362)

Add undeploy.yaml playbook

---

inventories/example_local/group_vars/all/dojot.yaml
roles/apigw/templates/apigw_routes_config_map.yaml.j2
roles/http-agent/defaults/main.yaml
roles/http-agent/templates/http_agent_cluster.yaml.j2
roles/http-agent/templates/http_agent_service.yaml.j2

[DEVOPS-383] add route insecure http-agent

---

inventories/example_local/group_vars/all/dojot.yaml

Bump to v0.8.0-rc.6

---

docs/vars.md
inventories/example_local/group_vars/all/dojot.yaml
roles/nginx/tasks/main.yaml
roles/nginx/tasks/self-signed-certificate-nginx.yaml
roles/nginx/templates/apigw_https_self_signed_certificate.conf.j2

[Ansible-dojot] Self Signed Certificate Nginx
[DEVOPS-435](https://jira.cpqd.com.br/browse/DEVOPS-435) [DOJOT] Ambiente de teste (e outros) deve ter https para acessos ao Kong

[DEVOPS-435] Kubernetes - Self Signed Certificate Nginx

---

roles/metrics/README.md
roles/metrics/templates/monitoring-stack/stack-values.yml.j2

docs update 
Currently the documentation refers to the solution without the changes applied with kube-prometheus-stack, that is, the documentation is outdated.
Now the documentation is in accordance with the solution being deployed.
No

Documentation update

---

inventories/example_local/group_vars/all/dojot.yaml

Bump to v0.8.0-rc.7

---

inventories/example_local/group_vars/all/dojot.yaml

bump to v0.8.0

---

roles/metrics/tasks/mongodb.yml
roles/metrics/tasks/rabbitmq.yml
roles/metrics/templates/mongodb-exporter/mongodb-exporter-values.yml.j2
roles/metrics/templates/monitoring-stack/stack-values.yml.j2

Bug fix and feature
The presentation of pods is happening incorrectly and it is not possible to know the health of the pods. Also, it is not possible to view the vernemq cluster in general.
Agora é possível visualizar os dados de forma mais declarativa e a saúde dos pods. Além de visualizar o cluster do vernemq de forma geral.
No
* **Is there any issue related to this PR in other …

Fixing Dashboards

---

roles/nginx/tasks/main.yaml

Remove old services from nginx

Remove old services from nginx

---

roles/vernemq/defaults/main.yaml

Bump to v0.8.1 - VMQ Operator Hot Fix

Bump to v0.8.1 - VMQ Operator Hot Fix

---

inventories/example_local/group_vars/all/dojot.yaml

Bump to dev-alpha.2

---

roles/influxdb-retriever/templates/influxdb_retriever_deployment.yaml.j2
roles/influxdb-retriever/templates/influxdb_retriever_service.yaml.j2

InfluxDB Retriever HotFix

---

roles/secrets/defaults/main.yaml

update secrets in the secrets service

---

inventories/example_local/group_vars/all/dojot.yaml

Bump to dev-alpha.3

---

inventories/example_local/group_vars/all/dojot.yaml

Bump to dev-alpha.4

---

deploy.yaml
roles/apigw/templates/apigw_routes_config_map.yaml.j2
roles/flowbroker/defaults/main.yaml
roles/flowbroker/tasks/main.yaml
roles/flowbroker/templates/flowbroker_deployment.yaml.j2
roles/flowbroker/templates/flowbroker_role.yaml.j2
roles/flowbroker/templates/flowbroker_role_binding.yaml.j2
roles/flowbroker/templates/flowbroker_service.yaml.j2
roles/flowbroker/templates/flowbroker_service_account.yaml.j2
roles/gui-nx/defaults/main.yaml
roles/gui-nx/tasks/main.yaml
roles/gui-nx/templates/flows_nx_deployment.yaml.j2
roles/gui-nx/templates/flows_nx_service.yaml.j2
roles/keycloak/confs/templates/customRealmRepresentation.json.j2
roles/rabbitmq/defaults/main.yaml
roles/rabbitmq/tasks/main.yaml
roles/rabbitmq/templates/rabbitmq_deployment.yaml.j2
roles/rabbitmq/templates/rabbitmq_service.yaml.j2
roles/report-manager/templates/report_manager_deployment.yaml.j2
roles/secrets/defaults/main.yaml
roles/secrets/templates/dojot_secrets.yaml.j2
roles/vault/confs/tasks/main.yaml

deploy flowbroker and fix report_manager

---

inventories/example_local/group_vars/all/dojot.yaml

Bump to v1.0.0-rc.1

---

roles/metrics/tasks/mongodb.yml
roles/metrics/templates/mongodb-exporter/mongodb-exporter-values.yml.j2
roles/metrics/templates/monitoring-stack/stack-values.yml.j2

Bug Fix
The prom operator service failed because of the amount of memory allocated and the mongo exporter failed due to a version problem. In addition to declaration errors, using hard code.
Now the prom operator service does not crash because of the amount of memory allocated, the mongo exporter has been updated and the declaration errors have been fixed
No
* **Is there any issue …

Fixing monitoring

---

inventories/example_local/group_vars/all/dojot.yaml

change version to development
